// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://huebxglhbenulbcftzdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1ZWJ4Z2xoYmVudWxiY2Z0emRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjQwMjcsImV4cCI6MjA3MDU0MDAyN30.j7GjRfvZbG6RwUPAYbFr1czTzPNISFPubOLK-Ciq2ZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  
  global: { headers: { 'Accept-Profile': 'app', 'Content-Profile': 'app' } },
});
